// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATSeNAnXFo8m5ZXqsiHBrLqIwkNwk1z3w',
    appId: '1:195531472939:web:e5d68169cd18a887f7ea6e',
    messagingSenderId: '195531472939',
    projectId: 'chat-app-c6348',
    authDomain: 'chat-app-c6348.firebaseapp.com',
    storageBucket: 'chat-app-c6348.appspot.com',
    measurementId: 'G-5TW974MSMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeibSWae-8BGiF34Krj4LIidvISLIwEmY',
    appId: '1:195531472939:android:eb0d381935d60ac5f7ea6e',
    messagingSenderId: '195531472939',
    projectId: 'chat-app-c6348',
    storageBucket: 'chat-app-c6348.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXLJGrGMEEczp5DzIQGoLuGZwREdN4NK4',
    appId: '1:195531472939:ios:ecb431e5df11118ff7ea6e',
    messagingSenderId: '195531472939',
    projectId: 'chat-app-c6348',
    storageBucket: 'chat-app-c6348.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXLJGrGMEEczp5DzIQGoLuGZwREdN4NK4',
    appId: '1:195531472939:ios:c1ba9a161ebc3bd9f7ea6e',
    messagingSenderId: '195531472939',
    projectId: 'chat-app-c6348',
    storageBucket: 'chat-app-c6348.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
